# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Staff platform3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!



  # Pods for Staff platform3

pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'IQKeyboardManagerSwift'
pod 'FirebaseFirestoreSwift', '> 7.0-beta'

end
